/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model() {
  const { nodes, materials } = useGLTF("/models/caja-amuleto.glb");
  return (
    <group dispose={null}>
      {/* Espuma */}

      {/* Espuma */}
      {/*  <mesh
        name="ESPUMA"
        castShadow
        receiveShadow
        geometry={nodes.ESPUMA.geometry}
        material={materials.ESPUMA}
        position={[-0.039, 0.019, 0.061]}
        scale={[33.656, 2.609, 50.892]}
      /> */}
      {/* Amueleto completo */}
      <group>
        <group
          name="AMULETO"
          position={[0.341, 0.138, -0.081]}
          scale={[0.255, 0.02, 0.285]}
        >
          <mesh
            name="Cube005"
            castShadow
            receiveShadow
            geometry={nodes.Cube005.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            name="Cube005_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube005_1.geometry}
            material={materials.Material}
          />
        </group>
        <group
          name="TAPA"
          position={[0.341, 0.138, -0.081]}
          scale={[0.255, 0.02, 0.285]}
          rotation={[0, 0, 0]}
        >
          <mesh
            name="Cube006"
            castShadow
            receiveShadow
            geometry={nodes.Cube006.geometry}
            material={materials.Material}
          />
          <mesh
            name="Cube006_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube006_1.geometry}
            material={materials["Material.006"]}
          />
        </group>
      </group>

      {/* Caja */}
      {/* <group
        name="CAJA_EXTERIOR"
        position={[-0.045, -0.012, -0.06]}
        rotation={[0, -1.568, 0]}
        scale={[1427.583, 1349.388, 1399.032]}
      >
        <mesh
          name="Cube_4"
          castShadow
          receiveShadow
          geometry={nodes.Cube_4.geometry}
          material={materials.CAJA}
        />
        <mesh
          name="Cube_4_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube_4_1.geometry}
          material={materials.foil}
        />
      </group> */}

      {/* <group>
        <mesh
          name="CAJA_FOTO"
          castShadow
          receiveShadow
          geometry={nodes.CAJA_FOTO.geometry}
          material={materials.CAJA}
          position={[-0.045, 0.007, -0.068]}
          rotation={[0, -1.568, 0]}
          scale={28.552}
        />
        <mesh
          name="FOTO"
          castShadow
          receiveShadow
          geometry={nodes.FOTO.geometry}
          material={nodes.FOTO.material}
          position={[-0.045, 0.228, -0.017]}
          scale={[24.84, 0.552, 35.47]}
        />
      </group> */}

      {/* Cajon magico */}
      {/* <mesh
        name="CAJA_DIJE"
        castShadow
        receiveShadow
        geometry={nodes.CAJA_DIJE.geometry}
        material={materials.CAJA}
        position={[-0.045, -0.012, -0.068]}
        rotation={[0, -1.568, 0]}
        scale={28.552}
      /> */}
    </group>
  );
}

useGLTF.preload("/models/caja-amuleto.glb");
